# Generated by Django 4.2 on 2023-04-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='id_like',
            new_name='is_like',
        ),
    ]
